# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CastText < Formula
  desc "a zero latency, easy-to-use full-text rss terminal reader."
  homepage "https://github.com/piqoni/cast-text"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.3/cast-text_Darwin_x86_64.tar.gz"
      sha256 "6a67fc45fa42b1e7e58e6719c36618c1d7413fd7eac09aaac5ac8bd8dd8b4de1"

      def install
        bin.install "cast-text"
      end
    end
    on_arm do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.3/cast-text_Darwin_arm64.tar.gz"
      sha256 "a44b51ff5f818c2a27b607bfbff86a2e58b1cad704efc38e510e26e0704616b1"

      def install
        bin.install "cast-text"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.3/cast-text_Linux_x86_64.tar.gz"
        sha256 "a66c94425d6d87ebb8d3f291529aba311e5064bb4ada30fb38c43af1daed7306"

        def install
          bin.install "cast-text"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.3/cast-text_Linux_arm64.tar.gz"
        sha256 "e0c4d41a1c8e9f773b883697087657a2000b4a929a776f3d9ee39987765eeef2"

        def install
          bin.install "cast-text"
        end
      end
    end
  end
end
