# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CastText < Formula
  desc "a zero latency, easy-to-use full-text rss terminal reader."
  homepage "https://github.com/piqoni/cast-text"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.1/cast-text_Darwin_x86_64.tar.gz"
      sha256 "eb9d38fb0d392723fa8e2f6a80c13c92c941b3ebfbba3dd08bbe3e9f49f98306"

      def install
        bin.install "cast-text"
      end
    end
    on_arm do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.1/cast-text_Darwin_arm64.tar.gz"
      sha256 "f6bf642f18abaa6a7a4f60d0aaaa1ecbd98c6fb41f56a4aed4d3e9283a7d20dd"

      def install
        bin.install "cast-text"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.1/cast-text_Linux_x86_64.tar.gz"
        sha256 "898777cdff94315b1c93fb1a3579fe90ff3c1c29bb30a49099a0a1cc79b209ee"

        def install
          bin.install "cast-text"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.1/cast-text_Linux_arm64.tar.gz"
        sha256 "a032cbfaf60d0028c552cba0813befd49dcd80a7dd7cc1889e105ed21f191e40"

        def install
          bin.install "cast-text"
        end
      end
    end
  end
end
