# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CastText < Formula
  desc "a zero latency, easy-to-use full-text rss terminal reader."
  homepage "https://github.com/piqoni/cast-text"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.0/cast-text_Darwin_x86_64.tar.gz"
      sha256 "e703e2363e2c06a0d2db57e3cd9d7ca016168e62b8e38a0972c81b54357eae14"

      def install
        bin.install "cast-text"
      end
    end
    on_arm do
      url "https://github.com/piqoni/cast-text/releases/download/v0.1.0/cast-text_Darwin_arm64.tar.gz"
      sha256 "bba603f31c2ee94be87f1acf04a95a3d69944b4da230c1591071db00a84a694f"

      def install
        bin.install "cast-text"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.0/cast-text_Linux_x86_64.tar.gz"
        sha256 "48201b660f359d2d310d5ed2affc372b9d6687310f6525e3ab27164a289aa50f"

        def install
          bin.install "cast-text"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/piqoni/cast-text/releases/download/v0.1.0/cast-text_Linux_arm64.tar.gz"
        sha256 "9d8f700d1f1a11c1497ca47690dc473a18af573c8fc07873a611e1f7d90dca3d"

        def install
          bin.install "cast-text"
        end
      end
    end
  end
end
